name: Notify main site

on: [push]

jobs:
   notify:
      runs-on: ubuntu-latest
      steps:
       - name: Trigger main site rebuild
         run: |
            curl -X POST \
            -H "Authorization: token ${{ secrets.ORG_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/mdap-internship/mdap-internship.github.io/dispatches \
            -d '{"event_type": "intern-updated"}'